# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TLsVqTQjMAbVDQ26jfwT42k1z63YkKKZ
"""

>>> se= "Calculadora en Clase de Sistemas Expertos"
>>> print (se)
>>> print("")
import os

while 1:
  print("")
  print("C A L C U L A D O R A")
  print("")
  print("OPERACIONES DISPONIBLES")
  print("1. Suma")
  print("2. Resta")
  print("3. Multiplicación")
  print("4. División")
  print("5. SALIR")

  op=int(input("SELECCIONE OPERACIÓN: "))

  if op==5:
    print("SALISTE")
    break
  
  if op>5:
      print("Opción no valida, Digite nuevamente")
      break

  num1=float(input("Digite primer numero: "))
  num2=float(input("Digite segundo numero: "))
  if op==1:
    resultado=num1+num2
  elif op==2:
    resultado=num1-num2
  elif op==3:
      resultado=num1*num2
  elif op==4:
      resultado=num1/num2
  print("El resultado es: ", resultado)